/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReunioesRouteImport } from './routes/_authenticated/reunioes'
import { Route as AuthenticatedRavennaRouteImport } from './routes/_authenticated/ravenna'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedLinksRouteImport } from './routes/_authenticated/links'
import { Route as AuthenticatedHistoriaRouteImport } from './routes/_authenticated/historia'
import { Route as AuthenticatedEstudosRouteImport } from './routes/_authenticated/estudos'
import { Route as AuthenticatedDashboardCwRouteImport } from './routes/_authenticated/dashboard-cw'
import { Route as AuthenticatedDadosRouteImport } from './routes/_authenticated/dados'
import { Route as AuthenticatedCarreiraRouteImport } from './routes/_authenticated/carreira'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReunioesRoute = AuthenticatedReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRavennaRoute = AuthenticatedRavennaRouteImport.update({
  id: '/ravenna',
  path: '/ravenna',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinksRoute = AuthenticatedLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoriaRoute = AuthenticatedHistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstudosRoute = AuthenticatedEstudosRouteImport.update({
  id: '/estudos',
  path: '/estudos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardCwRoute =
  AuthenticatedDashboardCwRouteImport.update({
    id: '/dashboard-cw',
    path: '/dashboard-cw',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDadosRoute = AuthenticatedDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarreiraRoute = AuthenticatedCarreiraRouteImport.update({
  id: '/carreira',
  path: '/carreira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carreira': typeof AuthenticatedCarreiraRoute
  '/dados': typeof AuthenticatedDadosRoute
  '/dashboard-cw': typeof AuthenticatedDashboardCwRoute
  '/estudos': typeof AuthenticatedEstudosRoute
  '/historia': typeof AuthenticatedHistoriaRoute
  '/links': typeof AuthenticatedLinksRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/ravenna': typeof AuthenticatedRavennaRoute
  '/reunioes': typeof AuthenticatedReunioesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carreira': typeof AuthenticatedCarreiraRoute
  '/dados': typeof AuthenticatedDadosRoute
  '/dashboard-cw': typeof AuthenticatedDashboardCwRoute
  '/estudos': typeof AuthenticatedEstudosRoute
  '/historia': typeof AuthenticatedHistoriaRoute
  '/links': typeof AuthenticatedLinksRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/ravenna': typeof AuthenticatedRavennaRoute
  '/reunioes': typeof AuthenticatedReunioesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/carreira': typeof AuthenticatedCarreiraRoute
  '/_authenticated/dados': typeof AuthenticatedDadosRoute
  '/_authenticated/dashboard-cw': typeof AuthenticatedDashboardCwRoute
  '/_authenticated/estudos': typeof AuthenticatedEstudosRoute
  '/_authenticated/historia': typeof AuthenticatedHistoriaRoute
  '/_authenticated/links': typeof AuthenticatedLinksRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/ravenna': typeof AuthenticatedRavennaRoute
  '/_authenticated/reunioes': typeof AuthenticatedReunioesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carreira'
    | '/dados'
    | '/dashboard-cw'
    | '/estudos'
    | '/historia'
    | '/links'
    | '/metas'
    | '/perfil'
    | '/pipeline'
    | '/planos'
    | '/ravenna'
    | '/reunioes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carreira'
    | '/dados'
    | '/dashboard-cw'
    | '/estudos'
    | '/historia'
    | '/links'
    | '/metas'
    | '/perfil'
    | '/pipeline'
    | '/planos'
    | '/ravenna'
    | '/reunioes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/carreira'
    | '/_authenticated/dados'
    | '/_authenticated/dashboard-cw'
    | '/_authenticated/estudos'
    | '/_authenticated/historia'
    | '/_authenticated/links'
    | '/_authenticated/metas'
    | '/_authenticated/perfil'
    | '/_authenticated/pipeline'
    | '/_authenticated/planos'
    | '/_authenticated/ravenna'
    | '/_authenticated/reunioes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reunioes': {
      id: '/_authenticated/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof AuthenticatedReunioesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ravenna': {
      id: '/_authenticated/ravenna'
      path: '/ravenna'
      fullPath: '/ravenna'
      preLoaderRoute: typeof AuthenticatedRavennaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links': {
      id: '/_authenticated/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AuthenticatedLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historia': {
      id: '/_authenticated/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof AuthenticatedHistoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudos': {
      id: '/_authenticated/estudos'
      path: '/estudos'
      fullPath: '/estudos'
      preLoaderRoute: typeof AuthenticatedEstudosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-cw': {
      id: '/_authenticated/dashboard-cw'
      path: '/dashboard-cw'
      fullPath: '/dashboard-cw'
      preLoaderRoute: typeof AuthenticatedDashboardCwRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dados': {
      id: '/_authenticated/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof AuthenticatedDadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carreira': {
      id: '/_authenticated/carreira'
      path: '/carreira'
      fullPath: '/carreira'
      preLoaderRoute: typeof AuthenticatedCarreiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCarreiraRoute: typeof AuthenticatedCarreiraRoute
  AuthenticatedDadosRoute: typeof AuthenticatedDadosRoute
  AuthenticatedDashboardCwRoute: typeof AuthenticatedDashboardCwRoute
  AuthenticatedEstudosRoute: typeof AuthenticatedEstudosRoute
  AuthenticatedHistoriaRoute: typeof AuthenticatedHistoriaRoute
  AuthenticatedLinksRoute: typeof AuthenticatedLinksRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedRavennaRoute: typeof AuthenticatedRavennaRoute
  AuthenticatedReunioesRoute: typeof AuthenticatedReunioesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCarreiraRoute: AuthenticatedCarreiraRoute,
  AuthenticatedDadosRoute: AuthenticatedDadosRoute,
  AuthenticatedDashboardCwRoute: AuthenticatedDashboardCwRoute,
  AuthenticatedEstudosRoute: AuthenticatedEstudosRoute,
  AuthenticatedHistoriaRoute: AuthenticatedHistoriaRoute,
  AuthenticatedLinksRoute: AuthenticatedLinksRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedRavennaRoute: AuthenticatedRavennaRoute,
  AuthenticatedReunioesRoute: AuthenticatedReunioesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
